# Generated by Django 5.0.3 on 2024-03-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('analysis_result', models.JSONField()),
                ('prompt', models.TextField(default='placeholder')),
                ('flag', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_hash', models.CharField(default='1234', max_length=255, unique=True)),
            ],
        ),
    ]
