# Generated by Django 5.0.3 on 2024-03-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_screenshots_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='prompt',
            field=models.TextField(default='placeholder'),
        ),
    ]
