# Generated by Django 5.0.3 on 2024-03-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_screenshot_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
