pipeline:
  identifier: Build_JishvaShah_LLM_Assisted_App_Compatibility_Test_1712449618795
  name: Build LLM-Assisted-App-Compatibility-Test
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1712449595936
        repoName: JishvaShah/LLM-Assisted-App-Compatibility-Test
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
